name = "womp-womp"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#d1-databases
[[d1_databases]]
binding = "WOMP_DB"
database_name = "WOMP_DB"
database_id = "b32bf941-f600-4779-ac2c-04cdbc7afa43"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#kv-namespaces
[[kv_namespaces]]
binding = "WOMP_KV"
id = "ef6cf0e31dc24cffa71fc6a91969ed90"
